// Generated by `supabase gen types` (via the Supabase MCP) from the hosted project
// nqaitmbwmuwpnpqatsfs. Do not edit by hand — regenerate after any migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      gather_assignments: {
        Row: {
          id: string
          last_collected_at: string
          player_character_id: string
          player_id: string
          resource_id: string
          started_at: string
        }
        Insert: {
          id?: string
          last_collected_at?: string
          player_character_id: string
          player_id: string
          resource_id: string
          started_at?: string
        }
        Update: {
          id?: string
          last_collected_at?: string
          player_character_id?: string
          player_id?: string
          resource_id?: string
          started_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "gather_assignments_player_character_id_fkey"
            columns: ["player_character_id"]
            isOneToOne: true
            referencedRelation: "player_characters"
            referencedColumns: ["id"]
          },
        ]
      }
      mission_runs: {
        Row: {
          ends_at: string
          id: string
          mission_def_id: string
          party: string[]
          player_id: string
          started_at: string
        }
        Insert: {
          ends_at: string
          id?: string
          mission_def_id: string
          party: string[]
          player_id: string
          started_at?: string
        }
        Update: {
          ends_at?: string
          id?: string
          mission_def_id?: string
          party?: string[]
          player_id?: string
          started_at?: string
        }
        Relationships: []
      }
      player_characters: {
        Row: {
          acquired_at: string
          blessings: Json
          character_def_id: string
          current_hp: number | null
          equipped: Json
          id: string
          level: number
          player_id: string
          xp: number
        }
        Insert: {
          acquired_at?: string
          blessings?: Json
          character_def_id: string
          current_hp?: number | null
          equipped?: Json
          id?: string
          level?: number
          player_id: string
          xp?: number
        }
        Update: {
          acquired_at?: string
          blessings?: Json
          character_def_id?: string
          current_hp?: number | null
          equipped?: Json
          id?: string
          level?: number
          player_id?: string
          xp?: number
        }
        Relationships: []
      }
      player_inventory: {
        Row: {
          acquired_at: string
          id: string
          item_def_id: string
          player_id: string
          quantity: number
          rarity: string
        }
        Insert: {
          acquired_at?: string
          id?: string
          item_def_id: string
          player_id: string
          quantity?: number
          rarity: string
        }
        Update: {
          acquired_at?: string
          id?: string
          item_def_id?: string
          player_id?: string
          quantity?: number
          rarity?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          currencies: Json
          player_id: string
          resources: Json
          transcendence_count: number
        }
        Insert: {
          created_at?: string
          currencies?: Json
          player_id: string
          resources?: Json
          transcendence_count?: number
        }
        Update: {
          created_at?: string
          currencies?: Json
          player_id?: string
          resources?: Json
          transcendence_count?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      claim_mission: {
        Args: {
          p_char_updates: Json
          p_currencies: Json
          p_loot: Json
          p_player: string
          p_resources: Json
          p_run_id: string
        }
        Returns: Json
      }
      start_mission: {
        Args: {
          p_duration_seconds: number
          p_mission_def_id: string
          p_party: string[]
          p_player: string
        }
        Returns: {
          ends_at: string
          id: string
          mission_def_id: string
          party: string[]
          player_id: string
          started_at: string
        }
        SetofOptions: {
          from: "*"
          to: "mission_runs"
          isOneToOne: true
          isSetofReturn: false
        }
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
