/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type EncounterEnemy = {
  _type: "encounterEnemy";
  enemy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "enemyDef";
  };
  count?: number;
};

export type BlessingNode = {
  _type: "blessingNode";
  nodeId?: string;
  title?: string;
  description?: string;
  row?: number;
  col?: number;
  maxRank?: number;
  isUltimate?: boolean;
  effects?: Array<{
    _key: string;
  } & NodeEffect>;
  requires?: Array<string>;
};

export type NodeEffect = {
  _type: "nodeEffect";
  stat?: "attack" | "strength" | "agility" | "speed" | "intelligence" | "spellPower" | "haste" | "health" | "defense" | "critChance" | "critDamage" | "armorPen" | "dodge" | "block" | "resistance" | "healthRegen" | "healingPower" | "healingCrit" | "missionSpeedDecrease" | "gatherSpeed" | "gatherYield" | "magicFind" | "luck";
  kind?: "flat" | "pct";
  perRank?: number;
};

export type StatGrowth = {
  _type: "statGrowth";
  stat?: "attack" | "strength" | "agility" | "speed" | "intelligence" | "spellPower" | "haste" | "health" | "defense" | "critChance" | "critDamage" | "armorPen" | "dodge" | "block" | "resistance" | "healthRegen" | "healingPower" | "healingCrit" | "missionSpeedDecrease" | "gatherSpeed" | "gatherYield" | "magicFind" | "luck";
  perLevel?: number;
  milestones?: Array<{
    level?: number;
    bonus?: number;
    _type: "milestone";
    _key: string;
  }>;
};

export type StatValue = {
  _type: "statValue";
  stat?: "attack" | "strength" | "agility" | "speed" | "intelligence" | "spellPower" | "haste" | "health" | "defense" | "critChance" | "critDamage" | "armorPen" | "dodge" | "block" | "resistance" | "healthRegen" | "healingPower" | "healingCrit" | "missionSpeedDecrease" | "gatherSpeed" | "gatherYield" | "magicFind" | "luck";
  value?: number;
};

export type EncounterDef = {
  _id: string;
  _type: "encounterDef";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  encounterKey?: string;
  description?: string;
  enemies?: Array<{
    _key: string;
  } & EncounterEnemy>;
  timeLimitSeconds?: number;
};

export type EnemyDef = {
  _id: string;
  _type: "enemyDef";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  enemyKey?: string;
  archetype?: "bruiser" | "caster" | "tank" | "swarm" | "boss";
  tier?: number;
  sprite?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  health?: number;
  attack?: number;
  damageType?: "physical" | "magic";
  speed?: number;
  defense?: number;
  resistance?: number;
  block?: number;
  critChance?: number;
  critDamage?: number;
  armorPen?: number;
  dodge?: number;
  healthRegen?: number;
};

export type CharacterDef = {
  _id: string;
  _type: "characterDef";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  charKey?: string;
  charClass?: "Warrior" | "Death Knight" | "Rogue" | "Hunter" | "Warlock" | "Mage" | "Fighter" | "Priest" | "Shaman" | "Druid" | "Bard" | "Engineer" | "Brewmaster" | "Painter" | "Miner" | "Forester";
  role?: "tank" | "damage" | "healer" | "utility" | "gatherer";
  baseStats?: Array<{
    _key: string;
  } & StatValue>;
  growth?: Array<{
    _key: string;
  } & StatGrowth>;
  blessingTree?: Array<{
    _key: string;
  } & BlessingNode>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = EncounterEnemy | BlessingNode | NodeEffect | StatGrowth | StatValue | EncounterDef | EnemyDef | CharacterDef | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
